{
	"schema_version": "1.6.0",
	"id": "ALBA-2020:4437",
	"modified": "2020-11-03T19:30:30Z",
	"published": "2020-11-03T12:04:32Z",
	"summary": "python-setuptools bug fix and enhancement update",
	"details": "For detailed information on changes in this release, see the AlmaLinux Release Notes linked from the References section.",
	"affected": [
		{
			"package": {
				"ecosystem": "AlmaLinux:8",
				"name": "platform-python-setuptools"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "39.2.0-6.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/AlmaLinux/osv-database/blob/master/advisories/almalinux8/ALBA-2020:4437.json"
			}
		},
		{
			"package": {
				"ecosystem": "AlmaLinux:8",
				"name": "python3-setuptools"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "39.2.0-6.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/AlmaLinux/osv-database/blob/master/advisories/almalinux8/ALBA-2020:4437.json"
			}
		},
		{
			"package": {
				"ecosystem": "AlmaLinux:8",
				"name": "python3-setuptools-wheel"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "39.2.0-6.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/AlmaLinux/osv-database/blob/master/advisories/almalinux8/ALBA-2020:4437.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://errata.almalinux.org/8/ALBA-2020-4437.html"
		}
	]
}
