{
	"schema_version": "1.6.0",
	"id": "ALBA-2020:1669",
	"modified": "2021-11-12T10:20:55Z",
	"published": "2020-04-28T09:03:10Z",
	"summary": "python-networkx bug fix and enhancement update",
	"details": "For detailed information on changes in this release, see the AlmaLinux Release Notes linked from the References section.",
	"affected": [
		{
			"package": {
				"ecosystem": "AlmaLinux:8",
				"name": "python3-networkx"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.11-16.1.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/AlmaLinux/osv-database/blob/master/advisories/almalinux8/ALBA-2020:1669.json"
			}
		},
		{
			"package": {
				"ecosystem": "AlmaLinux:8",
				"name": "python3-networkx-core"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.11-16.1.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/AlmaLinux/osv-database/blob/master/advisories/almalinux8/ALBA-2020:1669.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://errata.almalinux.org/8/ALBA-2020-1669.html"
		}
	]
}
