{
	"schema_version": "1.6.0",
	"id": "ALSA-2024:3837",
	"modified": "2024-06-14T06:41:16Z",
	"published": "2024-06-11T00:00:00Z",
	"related": [
		"CVE-2024-2199",
		"CVE-2024-3657"
	],
	"summary": "Important: 389-ds-base security update",
	"details": "389 Directory Server is an LDAP version 3 (LDAPv3) compliant server. The base\npackages include the Lightweight Directory Access Protocol (LDAP) server and\ncommand-line utilities for server administration.\n\nSecurity Fix(es):\n\n* 389-ds-base: potential denial of service via specially crafted kerberos AS-REQ request (CVE-2024-3657)\n* 389-ds-base: Malformed userPassword may cause crash at do_modify in slapd/modify.c (CVE-2024-2199)\n\nFor more details about the security issue(s), including the impact, a CVSS\nscore, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
	"affected": [
		{
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "389-ds-base"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.4.5-8.el9_4"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/AlmaLinux/osv-database/blob/master/advisories/almalinux9/ALSA-2024:3837.json"
			}
		},
		{
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "389-ds-base-devel"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.4.5-8.el9_4"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/AlmaLinux/osv-database/blob/master/advisories/almalinux9/ALSA-2024:3837.json"
			}
		},
		{
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "389-ds-base-libs"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.4.5-8.el9_4"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/AlmaLinux/osv-database/blob/master/advisories/almalinux9/ALSA-2024:3837.json"
			}
		},
		{
			"package": {
				"ecosystem": "AlmaLinux:9",
				"name": "python3-lib389"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.4.5-8.el9_4"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://github.com/AlmaLinux/osv-database/blob/master/advisories/almalinux9/ALSA-2024:3837.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:3837"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2024-2199"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2024-3657"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/2267976"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/2274401"
		},
		{
			"type": "ADVISORY",
			"url": "https://errata.almalinux.org/9/ALSA-2024-3837.html"
		}
	]
}
